### PR TITLE
Add SiFive cores

### PR DESCRIPTION
**Pull request by dbarbi1**
PR to add SiFive IP cores to the list.

### CODE REVIEW

**Comment by dbarbi1** [comment]
Hi @mgielda, is there any specific process I need to go through to get this reviewed and merged?

**Comment by mgielda** [comment]
hi @dbarbi1 sorry, missed this one. Could you resolve the conflict? I think your changes include some merge conflict resolution markers.

**Comment by dbarbi1** [comment]
Should be good to go now @mgielda

**Comment by mgielda** [comment]
I forgot to thank you for the contribution! :)

**Pull request merged**
