### PR TITLE
Steel Core added to the cores list.

### PR DESCRIPTION
**Pull request by rafaelcalcada**
Adds [Steel](https://github.com/rafaelcalcada/steel-core) to the cores list.

### CODE REVIEW

**Comment by mgielda** [comment]
Thanks for the contribution! Can you explain the use of "20190608" for the spec level? not that I think it's a horrible idea, but it's the first time someone has used this scheme.

**Comment by rafaelcalcada** [comment]
Hi Michael! 20190608 is the privileged ISA spec document version. I've changed to the right number now (1.11).

**Comment by rafaelcalcada** [comment]
Hi Michael! 20190608 is the privileged ISA spec document version. I've
changed to the right number now (1.11).

Em qua., 29 de jul. de 2020 às 14:01, Michael Gielda <
notifications@github.com> escreveu:

**Comment by mgielda** [comment]
Perfect! Thank you for the contribution. Are you planning Iron, Titanium, Platinum core etc.? ;)

**Pull request merged**
